name: Deploy no Railway

on:
  push:
    branches:
      - develop  # Apenas quando houver merge na develop

jobs:
  deploy:
    runs-on: ubuntu-latest
    container: ghcr.io/railwayapp/cli:latest  # Usa o Railway CLI oficial

    env:
      SVC_ID: meu-service-id  # Substitua pelo ID do serviço no Railway
      RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}

    steps:
      - name: Checkout do Código
        uses: actions/checkout@v3

      - name: Fazer deploy para Railway
        run: railway up --service=${{ env.SVC_ID }}
