name: Deploy no Railway

on:
  push:
    branches:
      - develop  # Executa o deploy somente na branch develop

jobs:
  deploy:
    runs-on: ubuntu-latest
    container: ghcr.io/railwayapp/cli:latest  # Usa a imagem oficial do Railway CLI

    env:
      SVC_ID: ${{ secrets.SVC_ID }}         # O ID do serviço configurado no Railway (definido como secret no GitHub)
      RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}  # O token do Railway (também definido como secret)

    steps:
      - name: Checkout do Código
        uses: actions/checkout@v3

      - name: Debug Token
        run: |
          echo "Token Length: $(echo -n $RAILWAY_TOKEN | wc -c)"

      - name: Fazer deploy para Railway
        run: railway up --service=${{ env.SVC_ID }}
