name: Deploy no Railway

on:
  push:
    branches:
      - develop  # Apenas quando houver merge na develop

jobs:
  deploy:
    runs-on: ubuntu-latest
    container: ghcr.io/railwayapp/cli:latest  # Usa a imagem oficial do Railway CLI

    env:
      SVC_ID: ${{ secrets.SVC_ID }}          # Service ID configurado nos secrets do GitHub
      RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}  # Token do Railway configurado nos secrets

    steps:
      - name: Checkout do Código
        uses: actions/checkout@v3

      - name: Debug Token
        run: |
          echo "Token Length: $(echo -n $RAILWAY_TOKEN | wc -c)"

      - name: Salvar Railway Token no Arquivo
        run: |
          mkdir -p ~/.railway
          echo "$RAILWAY_TOKEN" > ~/.railway/token

      - name: Fazer deploy para Railway
        run: railway up --service=${{ env.SVC_ID }}
