name: Deploy no Railway

on:
  push:
    branches:
      - develop  # Apenas quando houver merge na develop

jobs:
  deploy:
    runs-on: ubuntu-latest
    container: ghcr.io/railwayapp/cli:latest  # Usa a imagem oficial do Railway CLI

    env:
      SVC_ID: ${{ secrets.SVC_ID }}  # ID do serviço configurado no GitHub Secrets
      RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}

    steps:
      - name: Checkout do Código
        uses: actions/checkout@v3

      - name: Debug Token
        run: |
          if [ -z "${{ secrets.RAILWAY_TOKEN }}" ]; then
            echo "🚨 RAILWAY_TOKEN não foi carregado!"
            exit 1
          else
            echo "✅ RAILWAY_TOKEN está carregado corretamente!"
          fi

      - name: Fazer deploy para Railway
        run: |
          export RAILWAY_TOKEN=${{ secrets.RAILWAY_TOKEN }}
          railway up --service=${{ env.SVC_ID }}
