name: Deploy no Railway

on:
  push:
    branches:
      - develop  # Apenas quando houver merge na develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do Código
        uses: actions/checkout@v2

      - name: Instalar Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Instalar Dependências
        run: npm install

      - name: Rodar os Testes
        run: npm test

      - name: Build da Aplicação
        run: npm run build

      - name: Instalar CLI do Railway
        run: npm i -g @railway/cli

      - name: Deploy
        run: railway up
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
